name: Deploy to Live Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy to live server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_USER: ${{ secrets.SSH_USERNAME }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_PATH: /var/www/satva/quintallstall
        run: |
          # Setup SSH
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

          # Add host to known_hosts
          ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts
          echo "âœ… SSH setup completed."

          echo "ðŸš€ Connecting to server and running backend tasks..."
          # Run migrate commands on live server
          ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << EOF
            echo "ðŸ“ Changing to quintallstall directory..."
            cd $REMOTE_PATH

            echo "ðŸ” Pulling latest code from main branch..."
            git pull origin main
            
            export NVM_DIR="\$HOME/.nvm"
            [ -s "\$NVM_DIR/nvm.sh" ] && \. "\$NVM_DIR/nvm.sh"
            nvm use 18
            
            echo "ðŸ› ï¸ Building admin on remote server..."
            cd $REMOTE_PATH/admin
            npm install
            npm run build
            
            echo "ðŸ› ï¸ Building storefront on remote server..."
            cd $REMOTE_PATH/storefront
            npm install 
            npm run build
            
            echo "ðŸ“ Changing to backend directory..."
            cd $REMOTE_PATH/backend

            echo "ðŸ“¦ Installing composer dependencies..."
            composer install
            
            echo "ðŸ§¹ Running migrations and seeders..."
            php artisan migrate:refresh --seed
            echo "âœ… Backend update complete."
          EOF

          echo "âœ… Deployment complete!"
